#############################################################################
# Makefile for building: libmana.a
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  mana.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++ -o Makefile mana.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wno-deprecated -Wno-write-strings -Wno-unused-result -Wno-format-security -O2 -fPIC -std=c++0x -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mana1.0.0
DISTDIR = /dalaran/mana/out/mana1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../out/

####### Files

SOURCES       = common.cpp \
		daemon.cpp \
		http.cpp \
		smtp.cpp \
		thread.cpp \
		quickmail/quickmail.c \
		quickmail/smtpsocket.c \
		parser.cpp \
		yaml.cpp \
		ssh.cpp \
		database.cpp \
		cypher.cpp \
		polarssl/bignum.c \
		polarssl/base64.c \
		polarssl/sha1.c \
		polarssl/rsa.c \
		polarssl/md.c \
		polarssl/oid.c \
		polarssl/asn1parse.c \
		polarssl/md_wrap.c \
		polarssl/aes.c \
		polarssl/aesni.c \
		polarssl/arc4.c \
		polarssl/asn1write.c \
		polarssl/blowfish.c \
		polarssl/camellia.c \
		polarssl/ccm.c \
		polarssl/certs.c \
		polarssl/cipher_wrap.c \
		polarssl/cipher.c \
		polarssl/ctr_drbg.c \
		polarssl/debug.c \
		polarssl/des.c \
		polarssl/dhm.c \
		polarssl/ecdh.c \
		polarssl/ecdsa.c \
		polarssl/ecp_curves.c \
		polarssl/ecp.c \
		polarssl/entropy_poll.c \
		polarssl/entropy.c \
		polarssl/error.c \
		polarssl/gcm.c \
		polarssl/havege.c \
		polarssl/hmac_drbg.c \
		polarssl/md2.c \
		polarssl/md4.c \
		polarssl/md5.c \
		polarssl/memory_buffer_alloc.c \
		polarssl/net.c \
		polarssl/padlock.c \
		polarssl/pem.c \
		polarssl/pk_wrap.c \
		polarssl/pk.c \
		polarssl/pkcs5.c \
		polarssl/pkcs11.c \
		polarssl/pkcs12.c \
		polarssl/pkparse.c \
		polarssl/pkwrite.c \
		polarssl/platform.c \
		polarssl/ripemd160.c \
		polarssl/sha256.c \
		polarssl/sha512.c \
		polarssl/ssl_cache.c \
		polarssl/ssl_ciphersuites.c \
		polarssl/ssl_cli.c \
		polarssl/ssl_cookie.c \
		polarssl/ssl_srv.c \
		polarssl/ssl_ticket.c \
		polarssl/ssl_tls.c \
		polarssl/threading.c \
		polarssl/timing.c \
		polarssl/version_features.c \
		polarssl/version.c \
		polarssl/x509_create.c \
		polarssl/x509_crl.c \
		polarssl/x509_crt.c \
		polarssl/x509_csr.c \
		polarssl/x509.c \
		polarssl/x509write_crt.c \
		polarssl/x509write_csr.c \
		polarssl/xtea.c 
OBJECTS       = ../out/common.o \
		../out/daemon.o \
		../out/http.o \
		../out/smtp.o \
		../out/thread.o \
		../out/quickmail.o \
		../out/smtpsocket.o \
		../out/parser.o \
		../out/yaml.o \
		../out/ssh.o \
		../out/database.o \
		../out/cypher.o \
		../out/bignum.o \
		../out/base64.o \
		../out/sha1.o \
		../out/rsa.o \
		../out/md.o \
		../out/oid.o \
		../out/asn1parse.o \
		../out/md_wrap.o \
		../out/aes.o \
		../out/aesni.o \
		../out/arc4.o \
		../out/asn1write.o \
		../out/blowfish.o \
		../out/camellia.o \
		../out/ccm.o \
		../out/certs.o \
		../out/cipher_wrap.o \
		../out/cipher.o \
		../out/ctr_drbg.o \
		../out/debug.o \
		../out/des.o \
		../out/dhm.o \
		../out/ecdh.o \
		../out/ecdsa.o \
		../out/ecp_curves.o \
		../out/ecp.o \
		../out/entropy_poll.o \
		../out/entropy.o \
		../out/error.o \
		../out/gcm.o \
		../out/havege.o \
		../out/hmac_drbg.o \
		../out/md2.o \
		../out/md4.o \
		../out/md5.o \
		../out/memory_buffer_alloc.o \
		../out/net.o \
		../out/padlock.o \
		../out/pem.o \
		../out/pk_wrap.o \
		../out/pk.o \
		../out/pkcs5.o \
		../out/pkcs11.o \
		../out/pkcs12.o \
		../out/pkparse.o \
		../out/pkwrite.o \
		../out/platform.o \
		../out/ripemd160.o \
		../out/sha256.o \
		../out/sha512.o \
		../out/ssl_cache.o \
		../out/ssl_ciphersuites.o \
		../out/ssl_cli.o \
		../out/ssl_cookie.o \
		../out/ssl_srv.o \
		../out/ssl_ticket.o \
		../out/ssl_tls.o \
		../out/threading.o \
		../out/timing.o \
		../out/version_features.o \
		../out/version.o \
		../out/x509_create.o \
		../out/x509_crl.o \
		../out/x509_crt.o \
		../out/x509_csr.o \
		../out/x509.o \
		../out/x509write_crt.o \
		../out/x509write_csr.o \
		../out/xtea.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		mana.pro mana.h \
		common.h \
		daemon.h \
		http.h \
		lib.h \
		smtp.h \
		thread.h \
		quickmail/quickmail.h \
		quickmail/smtpsocket.h \
		parser.h \
		yaml.h \
		ssh.h \
		database.h \
		cypher.h \
		polarssl/mbedtls/base64.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/config.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/md_internal.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/aesni.h \
		polarssl/mbedtls/arc4.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/blowfish.h \
		polarssl/mbedtls/bn_mul.h \
		polarssl/mbedtls/camellia.h \
		polarssl/mbedtls/ccm.h \
		polarssl/mbedtls/certs.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/cipher_internal.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/compat-1.3.h \
		polarssl/mbedtls/ctr_drbg.h \
		polarssl/mbedtls/debug.h \
		polarssl/mbedtls/des.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/entropy_poll.h \
		polarssl/mbedtls/entropy.h \
		polarssl/mbedtls/error.h \
		polarssl/mbedtls/gcm.h \
		polarssl/mbedtls/havege.h \
		polarssl/mbedtls/hmac_drbg.h \
		polarssl/mbedtls/md2.h \
		polarssl/mbedtls/md4.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/memory_buffer_alloc.h \
		polarssl/mbedtls/net.h \
		polarssl/mbedtls/padlock.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/pk_internal.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/pkcs5.h \
		polarssl/mbedtls/pkcs11.h \
		polarssl/mbedtls/pkcs12.h \
		polarssl/mbedtls/platform.h \
		polarssl/mbedtls/ripemd160.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/ssl_cache.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/ssl_cookie.h \
		polarssl/mbedtls/ssl_internal.h \
		polarssl/mbedtls/ssl_ticket.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/timing.h \
		polarssl/mbedtls/version.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509_csr.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/xtea.h common.cpp \
		daemon.cpp \
		http.cpp \
		smtp.cpp \
		thread.cpp \
		quickmail/quickmail.c \
		quickmail/smtpsocket.c \
		parser.cpp \
		yaml.cpp \
		ssh.cpp \
		database.cpp \
		cypher.cpp \
		polarssl/bignum.c \
		polarssl/base64.c \
		polarssl/sha1.c \
		polarssl/rsa.c \
		polarssl/md.c \
		polarssl/oid.c \
		polarssl/asn1parse.c \
		polarssl/md_wrap.c \
		polarssl/aes.c \
		polarssl/aesni.c \
		polarssl/arc4.c \
		polarssl/asn1write.c \
		polarssl/blowfish.c \
		polarssl/camellia.c \
		polarssl/ccm.c \
		polarssl/certs.c \
		polarssl/cipher_wrap.c \
		polarssl/cipher.c \
		polarssl/ctr_drbg.c \
		polarssl/debug.c \
		polarssl/des.c \
		polarssl/dhm.c \
		polarssl/ecdh.c \
		polarssl/ecdsa.c \
		polarssl/ecp_curves.c \
		polarssl/ecp.c \
		polarssl/entropy_poll.c \
		polarssl/entropy.c \
		polarssl/error.c \
		polarssl/gcm.c \
		polarssl/havege.c \
		polarssl/hmac_drbg.c \
		polarssl/md2.c \
		polarssl/md4.c \
		polarssl/md5.c \
		polarssl/memory_buffer_alloc.c \
		polarssl/net.c \
		polarssl/padlock.c \
		polarssl/pem.c \
		polarssl/pk_wrap.c \
		polarssl/pk.c \
		polarssl/pkcs5.c \
		polarssl/pkcs11.c \
		polarssl/pkcs12.c \
		polarssl/pkparse.c \
		polarssl/pkwrite.c \
		polarssl/platform.c \
		polarssl/ripemd160.c \
		polarssl/sha256.c \
		polarssl/sha512.c \
		polarssl/ssl_cache.c \
		polarssl/ssl_ciphersuites.c \
		polarssl/ssl_cli.c \
		polarssl/ssl_cookie.c \
		polarssl/ssl_srv.c \
		polarssl/ssl_ticket.c \
		polarssl/ssl_tls.c \
		polarssl/threading.c \
		polarssl/timing.c \
		polarssl/version_features.c \
		polarssl/version.c \
		polarssl/x509_create.c \
		polarssl/x509_crl.c \
		polarssl/x509_crt.c \
		polarssl/x509_csr.c \
		polarssl/x509.c \
		polarssl/x509write_crt.c \
		polarssl/x509write_csr.c \
		polarssl/xtea.c
QMAKE_TARGET  = mana
DESTDIR       = ../out/#avoid trailing-slash linebreak
TARGET        = libmana.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

staticlib: ../out/$(TARGET)

../out/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../out/ || mkdir -p ../out/
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	-$(DEL_FILE) ../out/$(TARGET)
	-$(MOVE) $(TARGET) ../out/ 


Makefile: mana.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		mana.pro
	$(QMAKE) -spec linux-g++ -o Makefile mana.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Prison.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
mana.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile mana.pro

qmake_all: FORCE


all: Makefile ../out/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../out/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

../out/common.o: common.cpp common.h \
		lib.h \
		win_dirent.h \
		thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/common.o common.cpp

../out/daemon.o: daemon.cpp daemon.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/daemon.o daemon.cpp

../out/http.o: http.cpp http.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h \
		libcurl.arm/curl.h \
		libcurl.arm/curlver.h \
		libcurl.arm/curlbuild.h \
		libcurl.arm/curlrules.h \
		libcurl.arm/easy.h \
		libcurl.arm/multi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/http.o http.cpp

../out/smtp.o: smtp.cpp smtp.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h \
		quickmail/quickmail.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/smtp.o smtp.cpp

../out/thread.o: thread.cpp thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/thread.o thread.cpp

../out/quickmail.o: quickmail/quickmail.c quickmail/quickmail.h \
		quickmail/smtpsocket.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/quickmail.o quickmail/quickmail.c

../out/smtpsocket.o: quickmail/smtpsocket.c quickmail/smtpsocket.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/smtpsocket.o quickmail/smtpsocket.c

../out/parser.o: parser.cpp parser.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/parser.o parser.cpp

../out/yaml.o: yaml.cpp yaml.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h \
		cypher.h \
		polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/base64.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/sha1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/yaml.o yaml.cpp

../out/ssh.o: ssh.cpp ssh.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/ssh.o ssh.cpp

../out/database.o: database.cpp database.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/database.o database.cpp

../out/cypher.o: cypher.cpp cypher.h \
		common.h \
		lib.h \
		win_dirent.h \
		thread.h \
		polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/base64.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/sha1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../out/cypher.o cypher.cpp

../out/bignum.o: polarssl/bignum.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/bn_mul.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/bignum.o polarssl/bignum.c

../out/base64.o: polarssl/base64.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/base64.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/base64.o polarssl/base64.c

../out/sha1.o: polarssl/sha1.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/sha1.o polarssl/sha1.c

../out/rsa.o: polarssl/rsa.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/platform.h \
		polarssl/mbedtls/sha1.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/rsa.o polarssl/rsa.c

../out/md.o: polarssl/md.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/md_internal.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/md.o polarssl/md.c

../out/oid.o: polarssl/oid.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/oid.o polarssl/oid.c

../out/asn1parse.o: polarssl/asn1parse.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/asn1parse.o polarssl/asn1parse.c

../out/md_wrap.o: polarssl/md_wrap.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/md_internal.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/md2.h \
		polarssl/mbedtls/md4.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/ripemd160.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/md_wrap.o polarssl/md_wrap.c

../out/aes.o: polarssl/aes.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/padlock.h \
		polarssl/mbedtls/aesni.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/aes.o polarssl/aes.c

../out/aesni.o: polarssl/aesni.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/aesni.h \
		polarssl/mbedtls/aes.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/aesni.o polarssl/aesni.c

../out/arc4.o: polarssl/arc4.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/arc4.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/arc4.o polarssl/arc4.c

../out/asn1write.o: polarssl/asn1write.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/asn1write.o polarssl/asn1write.c

../out/blowfish.o: polarssl/blowfish.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/blowfish.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/blowfish.o polarssl/blowfish.c

../out/camellia.o: polarssl/camellia.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/camellia.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/camellia.o polarssl/camellia.c

../out/ccm.o: polarssl/ccm.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ccm.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ccm.o polarssl/ccm.c

../out/certs.o: polarssl/certs.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/certs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/certs.o polarssl/certs.c

../out/cipher_wrap.o: polarssl/cipher_wrap.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/cipher_internal.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/arc4.h \
		polarssl/mbedtls/camellia.h \
		polarssl/mbedtls/des.h \
		polarssl/mbedtls/blowfish.h \
		polarssl/mbedtls/gcm.h \
		polarssl/mbedtls/ccm.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/cipher_wrap.o polarssl/cipher_wrap.c

../out/cipher.o: polarssl/cipher.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/cipher_internal.h \
		polarssl/mbedtls/gcm.h \
		polarssl/mbedtls/ccm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/cipher.o polarssl/cipher.c

../out/ctr_drbg.o: polarssl/ctr_drbg.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ctr_drbg.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ctr_drbg.o polarssl/ctr_drbg.c

../out/debug.o: polarssl/debug.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/debug.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/debug.o polarssl/debug.c

../out/des.o: polarssl/des.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/des.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/des.o polarssl/des.c

../out/dhm.o: polarssl/dhm.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/dhm.o polarssl/dhm.c

../out/ecdh.o: polarssl/ecdh.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/bignum.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ecdh.o polarssl/ecdh.c

../out/ecdsa.o: polarssl/ecdsa.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/hmac_drbg.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ecdsa.o polarssl/ecdsa.c

../out/ecp_curves.o: polarssl/ecp_curves.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/bignum.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ecp_curves.o polarssl/ecp_curves.c

../out/ecp.o: polarssl/ecp.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ecp.o polarssl/ecp.c

../out/entropy_poll.o: polarssl/entropy_poll.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/entropy.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/havege.h \
		polarssl/mbedtls/entropy_poll.h \
		polarssl/mbedtls/timing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/entropy_poll.o polarssl/entropy_poll.c

../out/entropy.o: polarssl/entropy.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/entropy.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/havege.h \
		polarssl/mbedtls/entropy_poll.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/entropy.o polarssl/entropy.c

../out/error.o: polarssl/error.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/error.h \
		polarssl/mbedtls/platform.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/base64.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/blowfish.h \
		polarssl/mbedtls/camellia.h \
		polarssl/mbedtls/ccm.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/ctr_drbg.h \
		polarssl/mbedtls/des.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/entropy.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/havege.h \
		polarssl/mbedtls/gcm.h \
		polarssl/mbedtls/hmac_drbg.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/net.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/padlock.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/pkcs12.h \
		polarssl/mbedtls/pkcs5.h \
		polarssl/mbedtls/xtea.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/error.o polarssl/error.c

../out/gcm.o: polarssl/gcm.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/gcm.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/aesni.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/gcm.o polarssl/gcm.c

../out/havege.o: polarssl/havege.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/havege.h \
		polarssl/mbedtls/timing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/havege.o polarssl/havege.c

../out/hmac_drbg.o: polarssl/hmac_drbg.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/hmac_drbg.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/hmac_drbg.o polarssl/hmac_drbg.c

../out/md2.o: polarssl/md2.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/md2.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/md2.o polarssl/md2.c

../out/md4.o: polarssl/md4.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/md4.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/md4.o polarssl/md4.c

../out/md5.o: polarssl/md5.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/md5.o polarssl/md5.c

../out/memory_buffer_alloc.o: polarssl/memory_buffer_alloc.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/memory_buffer_alloc.h \
		polarssl/mbedtls/platform.h \
		polarssl/mbedtls/threading.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/memory_buffer_alloc.o polarssl/memory_buffer_alloc.c

../out/net.o: polarssl/net.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/net.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/net.o polarssl/net.c

../out/padlock.o: polarssl/padlock.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/padlock.h \
		polarssl/mbedtls/aes.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/padlock.o polarssl/padlock.c

../out/pem.o: polarssl/pem.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/base64.h \
		polarssl/mbedtls/des.h \
		polarssl/mbedtls/aes.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pem.o polarssl/pem.c

../out/pk_wrap.o: polarssl/pk_wrap.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pk_internal.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pk_wrap.o polarssl/pk_wrap.c

../out/pk.o: polarssl/pk.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/pk_internal.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pk.o polarssl/pk.c

../out/pkcs5.o: polarssl/pkcs5.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pkcs5.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pkcs5.o polarssl/pkcs5.c

../out/pkcs11.o: polarssl/pkcs11.c polarssl/mbedtls/pkcs11.h \
		polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pkcs11.o polarssl/pkcs11.c

../out/pkcs12.o: polarssl/pkcs12.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pkcs12.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/arc4.h \
		polarssl/mbedtls/des.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pkcs12.o polarssl/pkcs12.c

../out/pkparse.o: polarssl/pkparse.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/pkcs5.h \
		polarssl/mbedtls/pkcs12.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pkparse.o polarssl/pkparse.c

../out/pkwrite.o: polarssl/pkwrite.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/pkwrite.o polarssl/pkwrite.c

../out/platform.o: polarssl/platform.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/platform.o polarssl/platform.c

../out/ripemd160.o: polarssl/ripemd160.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ripemd160.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ripemd160.o polarssl/ripemd160.c

../out/sha256.o: polarssl/sha256.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/sha256.o polarssl/sha256.c

../out/sha512.o: polarssl/sha512.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/sha512.o polarssl/sha512.c

../out/ssl_cache.o: polarssl/ssl_cache.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ssl_cache.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_cache.o polarssl/ssl_cache.c

../out/ssl_ciphersuites.o: polarssl/ssl_ciphersuites.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_ciphersuites.o polarssl/ssl_ciphersuites.c

../out/ssl_cli.o: polarssl/ssl_cli.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/debug.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/ssl_internal.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_cli.o polarssl/ssl_cli.c

../out/ssl_cookie.o: polarssl/ssl_cookie.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ssl_cookie.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/ssl_internal.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_cookie.o polarssl/ssl_cookie.c

../out/ssl_srv.o: polarssl/ssl_srv.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/debug.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/ssl_internal.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_srv.o polarssl/ssl_srv.c

../out/ssl_ticket.o: polarssl/ssl_ticket.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/ssl_ticket.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_ticket.o polarssl/ssl_ticket.c

../out/ssl_tls.o: polarssl/ssl_tls.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/debug.h \
		polarssl/mbedtls/ssl.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ssl_ciphersuites.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/dhm.h \
		polarssl/mbedtls/ecdh.h \
		polarssl/mbedtls/ssl_internal.h \
		polarssl/mbedtls/md5.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/sha256.h \
		polarssl/mbedtls/sha512.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/ssl_tls.o polarssl/ssl_tls.c

../out/threading.o: polarssl/threading.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/threading.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/threading.o polarssl/threading.c

../out/timing.o: polarssl/timing.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/platform.h \
		polarssl/mbedtls/timing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/timing.o polarssl/timing.c

../out/version_features.o: polarssl/version_features.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/version.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/version_features.o polarssl/version_features.c

../out/version.o: polarssl/version.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/version.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/version.o polarssl/version.c

../out/x509_create.o: polarssl/x509_create.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509_create.o polarssl/x509_create.c

../out/x509_crl.o: polarssl/x509_crl.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509_crl.o polarssl/x509_crl.c

../out/x509_crt.o: polarssl/x509_crt.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509_crt.o polarssl/x509_crt.c

../out/x509_csr.o: polarssl/x509_csr.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509_csr.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509_csr.o polarssl/x509_csr.c

../out/x509.o: polarssl/x509.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/pem.h \
		polarssl/mbedtls/platform.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/certs.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509.o polarssl/x509.c

../out/x509write_crt.o: polarssl/x509write_crt.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509_crt.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/x509_crl.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/sha1.h \
		polarssl/mbedtls/pem.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509write_crt.o polarssl/x509write_crt.c

../out/x509write_csr.o: polarssl/x509write_csr.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/x509_csr.h \
		polarssl/mbedtls/x509.h \
		polarssl/mbedtls/asn1.h \
		polarssl/mbedtls/bignum.h \
		polarssl/mbedtls/pk.h \
		polarssl/mbedtls/md.h \
		polarssl/mbedtls/rsa.h \
		polarssl/mbedtls/threading.h \
		polarssl/mbedtls/ecp.h \
		polarssl/mbedtls/ecdsa.h \
		polarssl/mbedtls/oid.h \
		polarssl/mbedtls/cipher.h \
		polarssl/mbedtls/asn1write.h \
		polarssl/mbedtls/pem.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/x509write_csr.o polarssl/x509write_csr.c

../out/xtea.o: polarssl/xtea.c polarssl/mbedtls/config.h \
		polarssl/mbedtls/check_config.h \
		polarssl/mbedtls/xtea.h \
		polarssl/mbedtls/platform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../out/xtea.o polarssl/xtea.c

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_FILE) ../out/$(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

